spring:
  application:
    name: playground
  banner:
    location: classpath:banner.txt
    charset: UTF-8
  flyway:
    locations: classpath:db/migration
    table: schema_history
    schemas:  public
    clean-disabled: false

  config:
    import: "configserver:http://localhost:8888"
